### PR TITLE
Break some rules to see if CI fails (Do not merge!)

### PR DESCRIPTION
**Pull request by MaureenHelm**

### CODE REVIEW

**Comment by andrewmclachlanadi** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_stm32 | https://github.com/zephyrproject-rtos/hal_stm32/commit/1bc72c299d0365c0ee2575a97918b22df0899e10 | https://github.com/zephyrproject-rtos/hal_stm32/pull/178 | [zephyrproject-rtos/hal_stm32#178/files](https://github.com/zephyrproject-rtos/hal_stm32/pull/178/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Comment by andrewmclachlanadi** [comment]
Hi @MaureenHelm  - there are some actions that appear to run only on the zephyrproject-rtos repo (e.g., https://github.com/andrewmclachlanadi/zephyr/actions/runs/5979512237/workflow).

I can tweak the files and run them here if you think that's worth it Vs. only running those necessary to do checks and tests. Let me know.

**Comment by MaureenHelm** [comment]
> Hi @MaureenHelm - there are some actions that appear to run only on the zephyrproject-rtos repo (e.g., [andrewmclachlanadi/zephyr/actions/runs/5979512237/workflow](https://github.com/andrewmclachlanadi/zephyr/actions/runs/5979512237/workflow)).
> 
> I can tweak the files and run them here if you think that's worth it Vs. only running those necessary to do checks and tests. Let me know.

No, I don't think we need to run those checks. The "Greet first time contributor" check should probably be configured to only run in the upstream repo. Want to try sending a PR?

**Comment by andrewmclachlanadi** [comment]
> > Hi @MaureenHelm - there are some actions that appear to run only on the zephyrproject-rtos repo (e.g., [andrewmclachlanadi/zephyr/actions/runs/5979512237/workflow](https://github.com/andrewmclachlanadi/zephyr/actions/runs/5979512237/workflow)).
> > I can tweak the files and run them here if you think that's worth it Vs. only running those necessary to do checks and tests. Let me know.
> 
> No, I don't think we need to run those checks. The "Greet first time contributor" check should probably be configured to only run in the upstream repo. Want to try sending a PR?

You mean contribute upstream? Happy to!

For this PR, let me know how you'd like to proceed here.

**Comment by andrewmclachlanadi** [comment]
> No, I don't think we need to run those checks. The "Greet first time contributor" check should probably be configured to only run in the upstream repo. Want to try sending a PR?

https://github.com/zephyrproject-rtos/zephyr/pull/62328

**Pull request closed without merging**
